import { NgModule } from '@angular/core';
import {
  MatSnackBarModule,
  MatDialogModule,
  MatToolbarModule,
  MatIconModule,
  MatSidenavModule,
  MatListModule,
  MatMenuModule,
  MatGridListModule,
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatSelectModule,
  MatCardModule,
  MatTooltipModule,
  MatExpansionModule,
  MatButtonToggleModule,
  MatSliderModule,
  MatChipsModule,
  MatTabsModule,
  MatDatepickerModule,
  MatRadioModule,
  MatNativeDateModule
} from '@angular/material';

@NgModule({
  imports: [
    MatSnackBarModule,
    MatDialogModule,
    MatToolbarModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatMenuModule,
    MatGridListModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatCardModule,
    MatTooltipModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatSliderModule,
    MatChipsModule,
    MatTabsModule,
    MatDatepickerModule,
    MatRadioModule,
    MatNativeDateModule
  ],
  exports: [
    MatSnackBarModule,
    MatDialogModule,
    MatToolbarModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatMenuModule,
    MatGridListModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatCardModule,
    MatTooltipModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatSliderModule,
    MatChipsModule,
    MatTabsModule,
    MatDatepickerModule,
    MatRadioModule,
    MatNativeDateModule
  ]
})
export class MaterialModule {}
